# Generated by Django 5.0.6 on 2024-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('tech', 'Technical'), ('hr', 'HR question'), ('bhbrl', 'Behavioural Question')], max_length=20)),
                ('question_text', models.TextField()),
            ],
        ),
    ]
